export const LINKS_LOADED = 'LINKS_LOADED';
export const LINK_REMOVED = 'LINK_REMOVED';
export const TOKEN_ACQUIRED = 'TOKEN_ACQUIRED';
export const INIT_PASSWORD_SET = 'INIT_PASSWORD_SET';
export const FINISH_PASSWORD_SET = 'PASSWORD_SET';
export const FINISH_PASSWORD_NOT_SET = 'PASSWORD_NOT_SET';
export const PASSWORD_REMOVED = 'PASSWORD_REMOVED';