export const TOKEN_ACQUIRED = 'TOKEN_ACQUIRED';

export const LINKS_LOADED = 'LINKS_LOADED';
export const LINK_REMOVED = 'LINK_REMOVED';

export const PASSWORD_INIT_SET = 'PASSWORD_INIT_SET';
export const PASSWORD_FINISH_SET = 'PASSWORD_FINISH_SET';
export const PASSWORD_REMOVED = 'PASSWORD_REMOVED';
export const PASSWORD_NOT_SET = 'PASSWORD_NOT_SET';
export const LINK_CHANGED = 'LINK_CHANGED';
